import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <div id='wrapper' className='max-w-4xl mx-auto p-2 md:p-4'>
          <Header />
          <main className=''>{children}</main>
        </div>
      </body>
    </html>
  )
}
